# Generated by Django 3.0.5 on 2025-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_time',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
